### ISSUE TITLE
AzureBatch on Windows 7

### ISSUE THREAD

**Issue by philipleaper** [Azure/BatchLabs#1332]
**Description**
I have downloaded BatchLabs ( Version 0.15.0 (0.15.0.050118.0001) )

I have this installed on a Windows 7 machine which was working at one point, but now won't start with the message:
```
C:\Users\804490\Documents\BatchLabs>
(node:3704) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Cannot find module './GenericProvider'
(node:3704) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```
I have tried uninstalling and re-installing.  Including dropping the installed version and using the portable version, but always fails with the same error.  I'd assume it's some missing node dependency, but I'm confused how it worked before if that's the case.

Any help greatly appreciated.

Thanks,
Phil

**Comment by philipleaper** [comment]
Thanks for the response.  I went to 0.15.1 (after a clean out / restart / checking no processes hanging around) and got the same error.  Went back to 0.14.1 and it seems to be working.  I really appreciate the speedy response, thanks.

**Comment by timotheeguerin** [comment]
This seems like an issue with the latest version then. I'll reopen to keep track of it

**Comment by timotheeguerin** [comment]
I setup a windows 7 VM and this worked fine for me.
Next time could you try to make sure: 
* There is no ghost instance of BatchLabs(Check in the task explorer)
* Clear the logs before starting to make sure its coming from the latest run.

**Comment by marcelvb** [comment]
I'm experiencing the same problem with BatchLabs 0.15.1 on Windows 10 Pro, version 1709, OS build 16299.371.

**Comment by marcelvb** [comment]
A little bit of extra info: the first time I started 0.15.1 I got the login screen, but after that nothing. The following times I didn't anything at all.

I reinstalled 0.14.1 and this version is working.

**Comment by marcelvb** [comment]
I'm on 0.15.1 again. When starting BatchLabs from the command prompt I see this message:

```
[13:51:26.528Z]  INFO: BatchLabs Main: Registered ms-batchlabs:// as a protocol for batchlabs
[13:51:26.652Z] ERROR: BatchLabs Main: Failed to load proxy settings
    Error: Error validating proxy. Returned 501 Not Implemented
        at Object.<anonymous> (C:\Program Files\BatchLabs\resources\app.asar\node_modules\get-proxy-settings\src\validate.ts:60:19)
        at Generator.throw (<anonymous>)
        at rejected (C:\Program Files\BatchLabs\resources\app.asar\node_modules\get-proxy-settings\dist\validate.js:5:65)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
[13:51:26.659Z] ERROR: BatchLabs Main: Unhandled promise error:
    TypeError: Cannot read property 'settings' of undefined
        at ProxySettingsManager.<anonymous> (C:\Program Files\BatchLabs\resources\app.asar\src\client\proxy\proxy-settings.ts:36:54)
        at Generator.throw (<anonymous>)
        at rejected (C:\Program Files\BatchLabs\resources\app.asar\build\client\proxy\proxy-settings.js:5:65)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```



No login screen or anything. Process is running and must be killed with Task Manager.

**Comment by timotheeguerin** [comment]
Seems like this is an issue with the proxy, are you using a proxy(Defined in windows?)

I fixed that issue I think in master could you try this build https://ci.appveyor.com/project/azure-batch/batchlabs/build/1.0.3764/artifacts

**Comment by marcelvb** [comment]
I tried that version and this one seems to work for me. It does however still show an error when starting from the command prompt:
```
[09:54:31.747Z]  INFO: BatchLabs Main: Registered ms-batchlabs:// as a protocol for batchlabs
[09:54:31.874Z] ERROR: BatchLabs Main: Failed to load proxy settings
    Error: Error validating proxy. Returned 501 Not Implemented
        at Object.<anonymous> (C:\Program Files\BatchLabs\resources\app.asar\node_modules\get-proxy-settings\src\validate.ts:60:19)
        at Generator.throw (<anonymous>)
        at rejected (C:\Program Files\BatchLabs\resources\app.asar\node_modules\get-proxy-settings\dist\validate.js:5:65)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
[09:54:33.086Z]  INFO: BatchLabs Main: Python path is: 'C:\Program Files\BatchLabs\resources\python-rpc\main', Args: 45032
[09:54:33.090Z]  INFO: BatchLabs Python: ========================= STARTING PYTHON RPC SERVER PROCESS =========================
[09:54:33.090Z]  INFO: BatchLabs Main: Python Rpc server started!
[09:54:33.463Z]  INFO: BatchLabs Main: Listing tenants response 200 OK
[09:54:35.065Z]  INFO: BatchLabs Main: Checking for update
[09:54:37.058Z]  INFO: BatchLabs Main: Update for version 0.15.1 is not available (latest version: 0.15.1, downgrade is disallowed.
```

**Comment by timotheeguerin** [comment]
Yeah so the problem here is BatchLabs detected some proxy settings but they don't seem to be valid. So now it raise an error saying it couldn't validate the settings but it will just ignore and not use a proxy.

Could you check what is your configuration for proxy in your system?
![image](https://user-images.githubusercontent.com/1031227/40552295-1aebd20c-5ff4-11e8-9151-20e63fc315d1.png)

Could you also check in the registry what is the value for `ProxyServer ` and `ProxyEnable`
at `HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings`

**Comment by timotheeguerin** [comment]
I'm going to close this issue. If you can reproduce again with 0.16.0+. Feel free to reopen
